"""empty message

Revision ID: 6534b8b57740
Revises: ea26dd417283
Create Date: 2021-11-27 22:53:55.383903

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6534b8b57740'
down_revision = 'ea26dd417283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='voting')
    op.drop_index('ix_voting_is_enable', table_name='voting')
    op.drop_column('voting', 'email')
    op.drop_column('voting', 'is_enable')
    op.drop_column('voting', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voting', sa.Column('password', mysql.VARCHAR(length=128), nullable=False))
    op.add_column('voting', sa.Column('is_enable', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('voting', sa.Column('email', mysql.VARCHAR(length=64), nullable=False))
    op.create_index('ix_voting_is_enable', 'voting', ['is_enable'], unique=False)
    op.create_index('email', 'voting', ['email'], unique=False)
    # ### end Alembic commands ###
