"""empty message

Revision ID: bafc4956ed16
Revises: 6534b8b57740
Create Date: 2021-12-03 23:52:10.621279

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bafc4956ed16'
down_revision = '6534b8b57740'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_delivery_status', table_name='delivery')
    op.drop_table('delivery')
    op.drop_index('email', table_name='company')
    op.drop_index('ix_company_is_enable', table_name='company')
    op.drop_index('name', table_name='company')
    op.drop_table('company')
    op.drop_index('ix_job_city', table_name='job')
    op.drop_index('ix_job_education', table_name='job')
    op.drop_index('ix_job_exp', table_name='job')
    op.drop_index('ix_job_is_enable', table_name='job')
    op.drop_index('ix_job_salary_max', table_name='job')
    op.drop_index('ix_job_salary_min', table_name='job')
    op.drop_table('job')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('salary_min', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('salary_max', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('company_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('treatment', mysql.TEXT(), nullable=True),
    sa.Column('exp', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('education', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=8), nullable=True),
    sa.Column('tags', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('is_enable', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='job_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_job_salary_min', 'job', ['salary_min'], unique=False)
    op.create_index('ix_job_salary_max', 'job', ['salary_max'], unique=False)
    op.create_index('ix_job_is_enable', 'job', ['is_enable'], unique=False)
    op.create_index('ix_job_exp', 'job', ['exp'], unique=False)
    op.create_index('ix_job_education', 'job', ['education'], unique=False)
    op.create_index('ix_job_city', 'job', ['city'], unique=False)
    op.create_table('company',
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('is_enable', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('website', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('logo', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('role', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('finance_stage', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('field', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('details', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'company', ['name'], unique=False)
    op.create_index('ix_company_is_enable', 'company', ['is_enable'], unique=False)
    op.create_index('email', 'company', ['email'], unique=False)
    op.create_table('delivery',
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('job_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('company_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('resume', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('status', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('company_response', mysql.VARCHAR(length=256), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='delivery_ibfk_1', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name='delivery_ibfk_2', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='delivery_ibfk_3', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_delivery_status', 'delivery', ['status'], unique=False)
    # ### end Alembic commands ###
